{{- if not .Values.strava.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountabilidash.fullname" . }}-strava
  labels:
    {{- include "accountabilidash.labels" . | nindent 4 }}
type: Opaque
stringData:
  strava-id: {{ .Values.strava.id | quote }}
  strava-secret: {{ .Values.strava.secret | quote }}
  token-encryption-key: {{ .Values.strava.tokenEncryptionKey | quote }}
{{- end }}
