"""create goals and goal_completions tables

Revision ID: 46a3ee2fb0d1
Revises: 7cc09675d69d
Create Date: 2026-02-11 01:43:43.948720

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46a3ee2fb0d1'
down_revision: str | Sequence[str] | None = '7cc09675d69d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('goal_type', sa.Enum('PERIODIC', 'ONE_TIME', name='goaltype'), nullable=False),
    sa.Column(
        'frequency',
        sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'),
        nullable=True,
    ),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('value_type', sa.Enum('NONE', 'NUMERIC', 'TEXT', name='valuetype'), nullable=False),
    sa.Column('value_unit', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('goal_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_goal_completions_goal_id'), 'goal_completions', ['goal_id'], unique=False,
    )
    op.create_index(
        'ix_goal_completions_goal_period', 'goal_completions',
        ['goal_id', 'period_start'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_completions_goal_period', table_name='goal_completions')
    op.drop_index(op.f('ix_goal_completions_goal_id'), table_name='goal_completions')
    op.drop_table('goal_completions')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
